import { AttendanceRecord } from '../types';

const LOCAL_RECORDS_KEY = 'man1_local_attendance_records';
let memoryRecordsCache: AttendanceRecord[] | null = null;

function saveLocalCache(records: AttendanceRecord[]) {
  memoryRecordsCache = [...records];
    try {
        localStorage.setItem(LOCAL_RECORDS_KEY, JSON.stringify(records));
          } catch (e) {}
            if (typeof window !== 'undefined') {
                window.dispatchEvent(new CustomEvent('presensi_updated', { detail: records }));
                  }
                  }

                  // 1. AMBIL REKAP: Langsung dari Server SQL Neon (Bebas Kuota Firebase)
                  export async function getAttendanceRecords(): Promise<{ data: AttendanceRecord[]; isFromCloud: boolean }> {
                    let records: AttendanceRecord[] = [];
                      let isFromCloud = true;

                        try {
                            const res = await fetch('/api/attendance', { headers: { Accept: 'application/json' } });
                                if (res.ok) {
                                      const result = await res.json();
                                            if (result.success && Array.isArray(result.data)) {
                                                    records = result.data;
                                                          }
                                                              } else {
                                                                    isFromCloud = false;
                                                                        }
                                                                          } catch (err) {
                                                                              isFromCloud = false;
                                                                                }

                                                                                  if (records.length === 0) {
                                                                                      try {
                                                                                            const raw = localStorage.getItem(LOCAL_RECORDS_KEY);
                                                                                                  if (raw) {
                                                                                                          const parsed = JSON.parse(raw);
                                                                                                                  if (Array.isArray(parsed) && parsed.length > 0) records = parsed;
                                                                                                                        }
                                                                                                                            } catch (e) {}
                                                                                                                              }

                                                                                                                                records.sort((a, b) => {
                                                                                                                                    const ta = a.created_at ? new Date(a.created_at).getTime() : 0;
                                                                                                                                        const tb = b.created_at ? new Date(b.created_at).getTime() : 0;
                                                                                                                                            return tb - ta;
                                                                                                                                              });

                                                                                                                                                if (records.length > 0) saveLocalCache(records);
                                                                                                                                                  return { data: records, isFromCloud };
                                                                                                                                                  }

                                                                                                                                                  // 2. PANTAU REAL-TIME: Polling Server SQL setiap 4 detik (Tanpa Firebase onSnapshot)
                                                                                                                                                  export function subscribeToAttendance(callback: (records: AttendanceRecord[]) => void) {
                                                                                                                                                    getAttendanceRecords().then((res) => callback(res.data));

                                                                                                                                                      const intervalId = setInterval(async () => {
                                                                                                                                                          try {
                                                                                                                                                                const res = await fetch('/api/attendance', { headers: { Accept: 'application/json' } });
                                                                                                                                                                      if (res.ok) {
                                                                                                                                                                              const result = await res.json();
                                                                                                                                                                                      if (result.success && Array.isArray(result.data)) {
                                                                                                                                                                                                saveLocalCache(result.data);
                                                                                                                                                                                                          callback(result.data);
                                                                                                                                                                                                                  }
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                            } catch {}
                                                                                                                                                                                                                              }, 4000);

                                                                                                                                                                                                                                return () => clearInterval(intervalId);
                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                // 3. SISWA KIRIM ABSENSI: Langsung simpan ke Database SQL Neon
                                                                                                                                                                                                                                export async function submitAttendanceRecord(
                                                                                                                                                                                                                                  record: Omit<AttendanceRecord, 'id'>
                                                                                                                                                                                                                                  ): Promise<{ success: boolean; record: AttendanceRecord; isCloud: boolean; message: string }> {
                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                        const res = await fetch('/api/attendance', {
                                                                                                                                                                                                                                              method: 'POST',
                                                                                                                                                                                                                                                    headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
                                                                                                                                                                                                                                                          body: JSON.stringify(record),
                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                  const result = await res.json();
                                                                                                                                                                                                                                                                      if (!res.ok) {
                                                                                                                                                                                                                                                                            throw new Error(result.message || 'Gagal menyimpan presensi');
                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                    const savedRecord = result.record as AttendanceRecord;
                                                                                                                                                                                                                                                                                        const current = memoryRecordsCache || [];
                                                                                                                                                                                                                                                                                            saveLocalCache([savedRecord, ...current.filter((r) => r.id !== savedRecord.id)]);

                                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                                      success: true,
                                                                                                                                                                                                                                                                                                            record: savedRecord,
                                                                                                                                                                                                                                                                                                                  isCloud: true,
                                                                                                                                                                                                                                                                                                                        message: result.message || 'Presensi berhasil dicatat di Server SQL.',
                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                              } catch (err: any) {
                                                                                                                                                                                                                                                                                                                                  if (err.message && (err.message.includes('sudah') || err.message.includes('tercatat'))) {
                                                                                                                                                                                                                                                                                                                                        throw err;
                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                const fallbackRecord: AttendanceRecord = {
                                                                                                                                                                                                                                                                                                                                                      id: `rec-local-${Date.now()}`,
                                                                                                                                                                                                                                                                                                                                                            ...record,
                                                                                                                                                                                                                                                                                                                                                                  created_at: record.created_at || new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                          const currentRecords = memoryRecordsCache || [];
                                                                                                                                                                                                                                                                                                                                                                              saveLocalCache([fallbackRecord, ...currentRecords]);

                                                                                                                                                                                                                                                                                                                                                                                  return {
                                                                                                                                                                                                                                                                                                                                                                                        success: true,
                                                                                                                                                                                                                                                                                                                                                                                              record: fallbackRecord,
                                                                                                                                                                                                                                                                                                                                                                                                    isCloud: false,
                                                                                                                                                                                                                                                                                                                                                                                                          message: 'Presensi tersimpan di perangkat.',
                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                // 4. KOREKSI STATUS GURU
                                                                                                                                                                                                                                                                                                                                                                                                                export async function updateRecordStatus(
                                                                                                                                                                                                                                                                                                                                                                                                                  id: string,
                                                                                                                                                                                                                                                                                                                                                                                                                    newStatus: AttendanceRecord['status'],
                                                                                                                                                                                                                                                                                                                                                                                                                      notes?: string
                                                                                                                                                                                                                                                                                                                                                                                                                      ): Promise<boolean> {
                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                            const res = await fetch(`/api/attendance?id=${encodeURIComponent(id)}`, {
                                                                                                                                                                                                                                                                                                                                                                                                                                  method: 'PATCH',
                                                                                                                                                                                                                                                                                                                                                                                                                                        headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                                                                                                                                                              body: JSON.stringify({ id, status: newStatus, notes }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (res.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (memoryRecordsCache) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const updated = memoryRecordsCache.map((r) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              r.id === id ? { ...r, status: newStatus, notes: notes ?? r.notes } : r
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              saveLocalCache(updated);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // 5. HAPUS DATA
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export async function deleteRecord(id: string): Promise<boolean> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const res = await fetch(`/api/attendance?id=${encodeURIComponent(id)}`, { method: 'DELETE' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (res.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (memoryRecordsCache) saveLocalCache(memoryRecordsCache.filter((r) => r.id !== id));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } catch {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export async function deleteAllAttendanceRecords(): Promise<boolean> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const res = await fetch('/api/attendance', { method: 'DELETE' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (res.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                saveLocalCache([]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export function getStoredConfig() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return { isConnected: true };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }