import { neon } from '@neondatabase/serverless';

function getDb() {
  const connectionString =
      process.env.POSTGRES_URL ||
          process.env.POSTGRES_PRISMA_URL ||
              process.env.DATABASE_URL ||
                  '';

                    if (!connectionString) return null;
                      return neon(connectionString);
                      }

                      let tableReady = false;

                      async function initTable(sql: any) {
                        if (tableReady) return;
                          try {
                              await sql`
                                    CREATE TABLE IF NOT EXISTS attendance_records (
                                            id VARCHAR(128) PRIMARY KEY,
                                                    name VARCHAR(255) NOT NULL,
                                                            class VARCHAR(64) NOT NULL,
                                                                    prayer_type VARCHAR(64) NOT NULL,
                                                                            status VARCHAR(64) NOT NULL,
                                                                                    ai_status TEXT,
                                                                                            ai_confidence REAL,
                                                                                                    gps_status TEXT,
                                                                                                            gps_distance REAL,
                                                                                                                    gps_coords JSONB,
                                                                                                                            snapshot_photo TEXT,
                                                                                                                                    notes TEXT,
                                                                                                                                            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                                                                                                                                                  );
                                                                                                                                                      `;
                                                                                                                                                          tableReady = true;
                                                                                                                                                            } catch (e) {
                                                                                                                                                                console.error('Init table error:', e);
                                                                                                                                                                  }
                                                                                                                                                                  }

                                                                                                                                                                  export default async function handler(req: any, res: any) {
                                                                                                                                                                    res.setHeader('Access-Control-Allow-Origin', '*');
                                                                                                                                                                      res.setHeader('Access-Control-Allow-Methods', 'GET,POST,OPTIONS');
                                                                                                                                                                        res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

                                                                                                                                                                          if (req.method === 'OPTIONS') return res.status(200).end();

                                                                                                                                                                            const sql = getDb();
                                                                                                                                                                              if (!sql) {
                                                                                                                                                                                  return res.status(500).json({ success: false, message: 'Database Neon SQL belum tersambung di Vercel.' });
                                                                                                                                                                                    }

                                                                                                                                                                                      await initTable(sql);

                                                                                                                                                                                        // 1. GURU BUKA REKAP: Ambil semua data absensi beserta foto
                                                                                                                                                                                          if (req.method === 'GET') {
                                                                                                                                                                                              const data = await sql`
                                                                                                                                                                                                    SELECT 
                                                                                                                                                                                                            id, name, class, prayer_type, status, 
                                                                                                                                                                                                                    ai_status, ai_confidence, gps_status, gps_distance, 
                                                                                                                                                                                                                            gps_coords, snapshot_photo, notes, 
                                                                                                                                                                                                                                    to_char(created_at AT TIME ZONE 'Asia/Jakarta', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') AS created_at
                                                                                                                                                                                                                                          FROM attendance_records
                                                                                                                                                                                                                                                ORDER BY created_at DESC
                                                                                                                                                                                                                                                      LIMIT 2000;
                                                                                                                                                                                                                                                          `;
                                                                                                                                                                                                                                                              return res.status(200).json({ success: true, data, count: data.length });
                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                  // 2. SISWA KIRIM ABSENSI: Simpan langsung ke database SQL
                                                                                                                                                                                                                                                                    if (req.method === 'POST') {
                                                                                                                                                                                                                                                                        const b = req.body || {};
                                                                                                                                                                                                                                                                            const id = b.id || `att-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`;
                                                                                                                                                                                                                                                                                const photo = b.snapshot_photo || b.photo_url || null;

                                                                                                                                                                                                                                                                                    await sql`
                                                                                                                                                                                                                                                                                          INSERT INTO attendance_records (
                                                                                                                                                                                                                                                                                                  id, name, class, prayer_type, status,
                                                                                                                                                                                                                                                                                                          ai_status, ai_confidence, gps_status, gps_distance,
                                                                                                                                                                                                                                                                                                                  gps_coords, snapshot_photo, notes, created_at
                                                                                                                                                                                                                                                                                                                        ) VALUES (
                                                                                                                                                                                                                                                                                                                                ${id},
                                                                                                                                                                                                                                                                                                                                        ${(b.name || '').trim()},
                                                                                                                                                                                                                                                                                                                                                ${(b.class || '').trim()},
                                                                                                                                                                                                                                                                                                                                                        ${b.prayer_type},
                                                                                                                                                                                                                                                                                                                                                                ${b.status || 'Hadir'},
                                                                                                                                                                                                                                                                                                                                                                        ${b.ai_status || null},
                                                                                                                                                                                                                                                                                                                                                                                ${b.ai_confidence || 100},
                                                                                                                                                                                                                                                                                                                                                                                        ${b.gps_status || 'Valid'},
                                                                                                                                                                                                                                                                                                                                                                                                ${b.gps_distance || 0},
                                                                                                                                                                                                                                                                                                                                                                                                        ${b.gps_coords ? JSON.stringify(b.gps_coords) : null},
                                                                                                                                                                                                                                                                                                                                                                                                                ${photo},
                                                                                                                                                                                                                                                                                                                                                                                                                        ${b.notes || null},
                                                                                                                                                                                                                                                                                                                                                                                                                                ${b.created_at ? new Date(b.created_at) : new Date()}
                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                          `;

                                                                                                                                                                                                                                                                                                                                                                                                                                              return res.status(201).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                    success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                          message: 'Presensi berhasil dicatat di Server SQL Madrasah.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                record: { ...b, id, snapshot_photo: photo }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return res.status(405).json({ error: 'Method not allowed' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // 4. DELETE /api/attendance?id=...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (method === 'DELETE') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const recordId = req.query?.id || req.body?.id || pathId;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (recordId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await sql`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          DELETE FROM attendance_records
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    WHERE id = ${recordId};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return res.status(200).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        message: `Data presensi ${recordId} berhasil dihapus dari SQL.`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Reset all records
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await sql`DELETE FROM attendance_records;`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return res.status(200).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  message: 'Seluruh rekaman presensi berhasil dikosongkan.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }